apiVersion: v1
kind: ServiceAccount
metadata:
  name: etronium-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etronium-lord
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etronium-tenant